const investors = [
  {
    id: 326,
    name: 'Jacob Jones',
    email: 'zuole@gizlawa.to',
    photo: '',
    phone: '(445) 969-5181',
    company: 'Hong Kong SAR China',
    city: 'Izpiwan',
    country: 'Uzbekistan',
    balance: 7689,
    age: '25',
    sphere: '',
    online: true,
    position: '',
    status: 'investor',
    manager: 'Pavlo Zibrov',
    tokens: 3727,
    ava: '',
    lastSeen: '23.02.2019',
    registrationDate: '23.02.2019',
  },
  {
    id: 7437,
    name: 'Don Sparks',
    email: 'usfuzow@pe.ao',
    photo: '',
    phone: '(909) 791-1259',
    company: 'Indonesia',
    city: 'Kapsahaz',
    country: 'Germany',
    balance: 26464,
    age: '21',
    sphere: '',
    online: false,
    position: '',
    status: 'investor',
    manager: 'Pavlo Zibrov',
    tokens: 4304,
    ava: '',
    lastSeen: '23.02.2019',
    registrationDate: '23.02.2019',
  },
  {
    id: 19619,
    name: 'Christopher Kelly',
    email: 'wetes@hovnocir.br',
    photo: '',
    phone: '(537) 521-5086',
    company: 'Belgium',
    city: 'Voigja',
    country: 'Ukraine',
    balance: 59996,
    age: '33',
    sphere: '',
    online: false,
    position: '',
    status: 'investor',
    manager: 'Pavlo Zibrov',
    tokens: 4197,
    ava: '',
    lastSeen: '23.02.2019',
    registrationDate: '23.02.2019',
  },
];

export default investors;

